#### Configure workflow matrix
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

#### NOTE: Use entries according to their directory/file structure in 'config'
####       e.g. raspberry ...

# Use this categorie to configure behaviour on pushes/pull requests against
# develop branch
# Each entry will be used in setup matrix

buildtest:
  # Raspberry Pi OS based images
  # - raspberry/rpi32
  - raspberry/rpi64
  # rpi 64 with KS
  # - raspberry/rpi64-ks

# This is used to setup release build chain.
# Each entry will be used in setup matrix for releases

release:
  # Raspberry Pi OS based images
  # - raspberry/rpi32
  - raspberry/rpi64
